DROP DATABASE IF EXISTS grifoauto;

CREATE DATABASE grifoauto;

USE grifoauto;

CREATE TABLE vehicle (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    modele VARCHAR (100) NOT NULL,
    years VARCHAR (11) NOT NULL,
    motor VARCHAR (50) NOT NULL,
    interior VARCHAR (25) NULL
);